### ISSUE TITLE
Let the notification stay until dismissed

### ISSUE THREAD

**Issue by weiatwork** [dbilgili/Soon#4]
Similar to what Calendar is doing. That can help avoid missing a notification.

~~Another option is to re-pop the notification every minute or so.~~ Just noticed there is a `every` keyword. But for one-off notifications, it still makes sense to let them stay. Thanks.

**Comment by dbilgili** [comment]
I totally agree with you. Last time I've checked, it was not possible to set this through Electron unless the app is registered under Apple Developer Program.

An alternative solution though is to set the alert style to `Alerts` manually under **System Preferences > Notifications**.

**Comment by weiatwork** [comment]
That alternative is a great suggestion. It works well. Thanks.
